version: '3'

services:
  db:
    image: postgres:9
    restart: unless-stopped
    container_name: uolDB
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: uol
    ports:
      - "5430:5432"
    networks:
      - db-network
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  db-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "coast.gabrielle@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "pwd"
    ports:
      - "16543:80"
    depends_on:
      - db
    networks:
      - db-network

networks:
  db-network:
    driver: bridge
